___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Data Analysis with Python <br>Project - 1</p><h1> - Traffic Police Stops <img src="https://docs.google.com/uc?id=17CPCwi3_VvzcS87TOsh4_U8eExOhL6Ki" class="img-fluid" alt="CLRSWY" width="200" height="100">

Does the ``gender`` of a driver have an impact on police behavior during a traffic stop? **In this chapter**, you will explore that question while practicing filtering, grouping, method chaining, Boolean math, string methods, and more!

***

## Examining traffic violations

Before comparing the violations being committed by each gender, you should examine the ``violations`` committed by all drivers to get a baseline understanding of the data.

In this exercise, you'll count the unique values in the ``violation`` column, and then separately express those counts as proportions.

> Before starting your work in this section **repeat the steps which you did in the previos chapter for preparing the data.** Continue to this chapter based on where you were in the end of the previous chapter.

In [19]:
import warnings
warnings.filterwarnings('ignore')
warnings.warn("this will not show")

In [20]:
import pandas as pd
ri =pd.read_csv("cleaned1.csv", nrows=50000, index_col=0)

In [21]:
ri.dropna(axis=1, how="all", inplace=True)

ri["driver_gender"].dropna(inplace=True)

ri.is_arrested = ri.is_arrested.astype("bool")

combined = ri["stop_date"] +" "+ ri["stop_time"]

pd.to_datetime(combined)

ri["stop_datetime"] = pd.to_datetime(combined)
    
ri.set_index("stop_datetime", inplace=True)

In [22]:
ri.head(5)

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,2005-01-02,01:55,Zone K1,600,M,1985.0,20.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2005-01-02 20:30:00,RI-2005-00002,2005-01-02,20:30,Zone X4,500,M,1987.0,18.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2005-01-04 11:30:00,RI-2005-00003,2005-01-04,11:30,Zone X1,0,NaN,NaN,NaN,NaN,NaN,...,False,NaN,NaN,False,NaN,True,NaN,NaN,False,Zone X1
2005-01-04 12:55:00,RI-2005-00004,2005-01-04,12:55,Zone X4,500,M,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-06 01:30:00,RI-2005-00005,2005-01-06,01:30,Zone X4,500,M,1978.0,27.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4

**INSTRUCTIONS**

*   Count the unique values in the ``violation`` column, to see what violations are being committed by all drivers.
*   Express the violation counts as proportions of the total.

In [23]:
ri["violation"].unique()

array(['Speeding', nan, 'Equipment', 'Other', 'Moving violation',
       'Registration/plates'], dtype=object)

In [24]:
ri["violation"].nunique()

5

In [25]:
ri["violation"].value_counts(dropna=False)

Speeding               36112
Moving violation        6522
Equipment               3022
NaN                     1988
Registration/plates     1463
Other                    893
Name: violation, dtype: int64

In [26]:
ri["violation"].value_counts(normalize = True, dropna=False)

Speeding               0.72224
Moving violation       0.13044
Equipment              0.06044
NaN                    0.03976
Registration/plates    0.02926
Other                  0.01786
Name: violation, dtype: float64

***

## Comparing violations by gender

The question we're trying to answer is whether male and female drivers tend to commit different types of traffic violations.

You'll first create a ``DataFrame`` for each gender, and then analyze the ``violations`` in each ``DataFrame`` separately.

**INSTRUCTIONS**

*   Create a ``DataFrame``, female, that only contains rows in which ``driver_gender`` is ``'F'``.
*   Create a ``DataFrame``, male, that only contains rows in which ``driver_gender`` is ``'M'``.
*   Count the ``violations`` committed by female drivers and express them as proportions.
*   Count the violations committed by male drivers and express them as proportions.

In [27]:
female = ri[ri["driver_gender"]=="F"]

In [28]:
female.head()

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,2005-02-24,01:20,Zone X3,200,F,1983.0,22.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
2005-03-14 10:00:00,RI-2005-00019,2005-03-14,10:00,Zone K3,300,F,1984.0,21.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
2005-03-29 23:20:00,RI-2005-00026,2005-03-29,23:20,Zone K3,300,F,1971.0,34.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2005-06-06 13:20:00,RI-2005-00035,2005-06-06,13:20,Zone X4,500,F,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-06-18 16:30:00,RI-2005-00037,2005-06-18,16:30,Zone X4,500,F,1964.0,41.0,W,White,...,False,NaN,NaN,False,Arrest Driver,True,30+ Min,False,False,Zone X4

In [29]:
female["violation"].value_counts(normalize = True, dropna=False)

Speeding               0.811180
Moving violation       0.099031
Equipment              0.045608
Registration/plates    0.027575
Other                  0.016605
Name: violation, dtype: float64

In [30]:
male = ri[ri["driver_gender"]=="M"]

In [31]:
male.head()

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,2005-01-02,01:55,Zone K1,600,M,1985.0,20.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2005-01-02 20:30:00,RI-2005-00002,2005-01-02,20:30,Zone X4,500,M,1987.0,18.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2005-01-04 12:55:00,RI-2005-00004,2005-01-04,12:55,Zone X4,500,M,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-06 01:30:00,RI-2005-00005,2005-01-06,01:30,Zone X4,500,M,1978.0,27.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-12 08:05:00,RI-2005-00006,2005-01-12,08:05,Zone X1,0,M,1973.0,32.0,B,Black,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1

In [32]:
male["violation"].value_counts(normalize = True, dropna=False)

Speeding               0.729518
Moving violation       0.149967
Equipment              0.069595
Registration/plates    0.031584
Other                  0.019337
Name: violation, dtype: float64

In [33]:
 ri.groupby(["driver_gender"]).violation.value_counts(normalize=True)

driver_gender  violation
F              Speeding               0.811180
               Moving violation       0.099031
               Equipment              0.045608
               Registration/plates    0.027575
               Other                  0.016605
M              Speeding               0.729518
               Moving violation       0.149967
               Equipment              0.069595
               Registration/plates    0.031584
               Other                  0.019337
Name: violation, dtype: float64

***

## Comparing speeding outcomes by gender

When a driver is pulled over for speeding, many people believe that gender has an impact on whether the driver will receive a ticket or a warning. Can you find evidence of this in the dataset?

First, you'll create two ``DataFrames`` of drivers who were stopped for ``speeding``: one containing ***females*** and the other containing ***males***.

Then, for each **gender**, you'll use the ``stop_outcome`` column to calculate what percentage of stops resulted in a ``"Citation"`` (meaning a ticket) versus a ``"Warning"``.

**INSTRUCTIONS**

*   Create a ``DataFrame``, ``female_and_speeding``, that only includes female drivers who were stopped for speeding.
*   Create a ``DataFrame``, ``male_and_speeding``, that only includes male drivers who were stopped for speeding.
*   Count the **stop outcomes** for the female drivers and express them as proportions.
*   Count the **stop outcomes** for the male drivers and express them as proportions.

In [34]:
ri["stop_outcome"].dropna(inplace=True)

In [35]:
female_and_speeding = ri[(ri.driver_gender=="F") & (ri.violation=="Speeding")]

male_and_speeding = ri[(ri.driver_gender=="M") & (ri.violation=="Speeding")]

In [36]:
female_and_speeding.head()

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,2005-02-24,01:20,Zone X3,200,F,1983.0,22.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
2005-03-14 10:00:00,RI-2005-00019,2005-03-14,10:00,Zone K3,300,F,1984.0,21.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
2005-03-29 23:20:00,RI-2005-00026,2005-03-29,23:20,Zone K3,300,F,1971.0,34.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2005-06-06 13:20:00,RI-2005-00035,2005-06-06,13:20,Zone X4,500,F,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-07-06 11:22:00,RI-2005-00038,2005-07-06,11:22,Zone X1,0,F,1973.0,32.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X1

In [37]:
ri.stop_outcome.value_counts(dropna=False)

Citation            43788
Arrest Driver        2268
Warning               871
N/D                   663
Arrest Passenger      220
No Action             202
Name: stop_outcome, dtype: int64

In [38]:
female_and_speeding.stop_outcome.value_counts(normalize=True)

Citation            0.973416
Warning             0.012968
Arrest Driver       0.007410
N/D                 0.003612
Arrest Passenger    0.002316
No Action           0.000278
Name: stop_outcome, dtype: float64

In [39]:
male_and_speeding.stop_outcome.value_counts(normalize=True)

Citation            0.957298
Arrest Driver       0.026230
Warning             0.010666
N/D                 0.003397
Arrest Passenger    0.002015
No Action           0.000395
Name: stop_outcome, dtype: float64

In [40]:
print(ri.stop_outcome.dtype)

object

***

## Calculating the search rate

During a traffic stop, the police officer sometimes conducts a search of the vehicle. In this exercise, you'll calculate the percentage of all stops that result in a vehicle search, also known as the **search rate**.

**INSTRUCTIONS**

*   Check the data type of ``search_conducted`` to confirm that it's a ``Boolean Series``.
*   Calculate the search rate by counting the ``Series`` values and expressing them as proportions.
*   Calculate the search rate by taking the mean of the ``Series``. (It should match the proportion of ``True`` values calculated above.)

In [42]:
ri.search_conducted.dtype

dtype('bool')

In [43]:
ri.search_conducted.value_counts(normalize=True)

False    0.95976
True     0.04024
Name: search_conducted, dtype: float64

In [44]:
ri.search_conducted.mean()

0.04024

***

## Comparing search rates by gender

You'll compare the rates at which **female** and **male** drivers are searched during a traffic stop. Remember that the vehicle search rate across all stops is about **3.8%**.

First, you'll filter the ``DataFrame`` by gender and calculate the search rate for each group separately. Then, you'll perform the same calculation for both genders at once using a ``.groupby()``.

**INSTRUCTIONS 1/3**

*   Filter the ``DataFrame`` to only include **female** drivers, and then calculate the search rate by taking the mean of ``search_conducted``.

In [45]:
ri[(ri.driver_gender=="F")  & (ri.search_conducted)].head()

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-10-02 09:20:00,RI-2005-00363,2005-10-02,09:20,Zone K2,900,F,1977.0,28.0,W,White,...,True,Incident to Arrest,Incident to Arrest,False,Arrest Passenger,True,16-30 Min,False,False,Zone K2
2005-10-05 03:00:00,RI-2005-00758,2005-10-05,03:00,Zone K2,900,F,1969.0,36.0,W,White,...,True,Incident to Arrest,Incident to Arrest,True,Arrest Driver,True,16-30 Min,False,True,Zone K2
2005-10-05 03:15:00,RI-2005-00759,2005-10-05,03:15,Zone K2,900,F,1969.0,36.0,W,White,...,True,Incident to Arrest,Incident to Arrest,False,N/D,False,30+ Min,False,False,Zone K2
2005-10-06 21:50:00,RI-2005-01028,2005-10-06,21:50,Zone X4,500,F,1953.0,52.0,W,White,...,True,Incident to Arrest,Incident to Arrest,True,Arrest Driver,True,30+ Min,False,False,Zone X4
2005-10-06 21:50:00,RI-2005-01029,2005-10-06,21:50,Zone X4,500,F,1953.0,52.0,W,White,...,True,Incident to Arrest,Incident to Arrest,True,Arrest Driver,True,30+ Min,False,False,Zone X4

In [46]:
ri[(ri.driver_gender=="F")].search_conducted.mean()

0.017807498685100308

**INSTRUCTIONS 2/3**

*   Filter the ``DataFrame`` to only include **male** drivers, and then repeat the search rate calculation.

In [47]:
ri[(ri.driver_gender=="M")].search_conducted.mean()

0.05115126365234431

**INSTRUCTIONS 3/3**

*   Group by driver gender to calculate the search rate for both groups simultaneously. (It should match the previous results.)

In [48]:
ri.groupby("driver_gender").search_conducted.mean()

driver_gender
F    0.017807
M    0.051151
Name: search_conducted, dtype: float64

***

## Adding a second factor to the analysis

Even though the search rate for males is much higher than for females, it's possible that the difference is mostly due to a second factor.

For example, you might hypothesize that the search rate varies by violation type, and the difference in search rate between males and females is because they tend to commit different violations.

You can test this hypothesis by examining the search rate for each combination of gender and violation. If the hypothesis was true, you would find that males and females are searched at about the same rate for each violation. Find out below if that's the case!

**INSTRUCTIONS 1/2**

*   Use a ``.groupby()`` to calculate the search rate for each combination of gender and violation. Are males and females searched at about the same rate for each violation?

In [49]:
ri.groupby(["driver_gender", "violation"]).search_conducted.mean()

driver_gender  violation
F              Equipment              0.079077
               Moving violation       0.047800
               Other                  0.045249
               Registration/plates    0.114441
               Speeding               0.006854
M              Equipment              0.123395
               Moving violation       0.088778
               Other                  0.154993
               Registration/plates    0.171533
               Speeding               0.028560
Name: search_conducted, dtype: float64

**INSTRUCTIONS 2/2**

*   Reverse the ordering to group by violation before gender. The results may be easier to compare when presented this way.

In [50]:
ri.groupby(["violation", "driver_gender"]).search_conducted.mean()

violation            driver_gender
Equipment            F                0.079077
                     M                0.123395
Moving violation     F                0.047800
                     M                0.088778
Other                F                0.045249
                     M                0.154993
Registration/plates  F                0.114441
                     M                0.171533
Speeding             F                0.006854
                     M                0.028560
Name: search_conducted, dtype: float64

***

## Counting protective frisks

During a vehicle search, the police officer may pat down the driver to check if they have a weapon. This is known as a ``"protective frisk."``

You'll first check to see how many times "Protective Frisk" was the only search type. Then, you'll use a string method to locate all instances in which the driver was frisked.

**INSTRUCTIONS**

*   Count the ``search_type`` values to see how many times ``"Protective Frisk"`` was the only search type.
*   Create a new column, frisk, that is ``True`` if ``search_type`` contains the string ``"Protective Frisk"`` and ``False`` otherwise.
*   Check the data type of frisk to confirm that it's a ``Boolean Series``.
*   Take the sum of frisk to count the total number of frisks.

In [51]:
ri.search_type.value_counts()

Incident to Arrest                                          958
Probable Cause                                              244
Protective Frisk                                            204
Inventory                                                   117
Incident to Arrest,Inventory                                116
Incident to Arrest,Probable Cause                            76
Incident to Arrest,Protective Frisk                          63
Reasonable Suspicion                                         43
Probable Cause,Protective Frisk                              36
Incident to Arrest,Inventory,Protective Frisk                33
Inventory,Protective Frisk                                   23
Incident to Arrest,Probable Cause,Protective Frisk           20
Incident to Arrest,Inventory,Probable Cause                  19
Protective Frisk,Reasonable Suspicion                        16
Inventory,Probable Cause                                     16
Probable Cause,Reasonable Suspicion                          12
Probable Cause,Protective Frisk,Reasonable Suspicion          5
Incident to Arrest,Reasonable Suspicion                       5
Inventory,Probable Cause,Protective Frisk                     2
Incident to Arrest,Probable Cause,Reasonable Suspicion        1
Incident to Arrest,Inventory,Reasonable Suspicion             1
Incident to Arrest,Protective Frisk,Reasonable Suspicion      1
Inventory,Reasonable Suspicion                                1
Name: search_type, dtype: int64

In [52]:
ri["frisk"]= ri.search_type.str.contains("Protective Frisk", na=False)

In [53]:
ri.frisk.dtype

dtype('bool')

In [54]:
ri.frisk.sum()

403

In [55]:
ri[ri.frisk].head()

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-09 03:05:00,RI-2005-00011,2005-02-09,03:05,Zone X4,500,M,1976.0,29.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",False,Citation,False,0-15 Min,False,False,Zone X4,True
2005-08-28 01:00:00,RI-2005-00084,2005-08-28,01:00,Zone X1,0,M,1979.0,26.0,W,White,...,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,16-30 Min,True,False,Zone X1,True
2005-10-01 16:20:00,RI-2005-00253,2005-10-01,16:20,Zone K1,600,M,1958.0,47.0,W,White,...,"Reasonable Suspicion,Terry Frisk","Protective Frisk,Reasonable Suspicion",True,Citation,False,16-30 Min,False,False,Zone K1,True
2005-10-06 21:35:00,RI-2005-01027,2005-10-06,21:35,Zone X4,500,M,1966.0,39.0,W,White,...,Terry Frisk,Protective Frisk,False,Citation,False,0-15 Min,False,False,Zone X4,True
2005-10-07 11:33:00,RI-2005-01121,2005-10-07,11:33,Zone X4,900,M,1980.0,25.0,W,White,...,Terry Frisk,Protective Frisk,False,Arrest Driver,True,16-30 Min,False,False,Zone X4,True

***

## Comparing frisk rates by gender

You'll compare the rates at which female and male drivers are frisked during a search. Are males frisked more often than females, perhaps because police officers consider them to be higher risk?

Before doing any calculations, it's important to filter the ``DataFrame`` to only include the relevant subset of data, namely stops in which a search was conducted.

**INSTRUCTIONS**

*   Create a ``DataFrame``, searched, that only contains rows in which ``search_conducted`` is ``True``.
*   Take the mean of the frisk column to find out what percentage of searches included a frisk.
*   Calculate the frisk rate for each gender using a ``.groupby()``.

In [56]:
searched = ri[ri.search_conducted]

In [57]:
searched

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-24 20:32:00,RI-2005-00010,2005-01-24,20:32,Zone K1,600,M,1987.0,18.0,W,White,...,Probable Cause,Probable Cause,True,Citation,False,0-15 Min,True,True,Zone K1,False
2005-02-09 03:05:00,RI-2005-00011,2005-02-09,03:05,Zone X4,500,M,1976.0,29.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",False,Citation,False,0-15 Min,False,False,Zone X4,True
2005-08-28 01:00:00,RI-2005-00084,2005-08-28,01:00,Zone X1,0,M,1979.0,26.0,W,White,...,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,16-30 Min,True,False,Zone X1,True
2005-09-15 02:20:00,RI-2005-00094,2005-09-15,02:20,Zone X4,500,M,1988.0,17.0,W,White,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone X4,False
2005-09-24 02:20:00,RI-2005-00115,2005-09-24,02:20,Zone K3,300,M,1987.0,18.0,W,White,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone K3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-07 23:40:00,RI-2006-35738,2006-08-07,23:40,Zone X3,200,F,1984.0,22.0,W,White,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone X3,False
2006-08-08 00:15:00,RI-2006-35744,2006-08-08,00:15,Zone K3,300,M,1971.0,35.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",True,Citation,False,16-30 Min,False,True,Zone K3,True
2006-08-08 00:15:00,RI-2006-35745,2006-08-08,00:15,Zone X4,500,M,1971.0,35.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",True,Citation,False,16-30 Min,False,True,Zone X4,True
2006-08-08 00:40:00,RI-2006-35750,2006-08-08,00:40,Zone K3,300,M,1986.0,20.0,H,Hispanic,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,30+ Min,False,False,Zone K3,False
2006-08-08 22:22:00,RI-2006-35912,2006-08-08,22:22,Zone K3,300,M,1957.0,49.0,W,White,...,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,0-15 Min,False,False,Zone K3,True

In [58]:
searched.frisk.mean()

0.20029821073558648

In [59]:
searched.groupby("driver_gender").frisk.mean()

driver_gender
F    0.164557
M    0.205070
Name: frisk, dtype: float64

In [60]:
print(ri.index.dtype)

datetime64[ns]

In [61]:
ri.to_csv("frisk.csv")